### ISSUE TITLE
Hourly forecast and more info in forecast

### ISSUE THREAD

**Issue by bruxy70** [Danielhiversen/pyMetno#14]
Hi. Would that be ok if I make a PR with some enhancements?
I'd like to add an optional parameter to get_forecast to get hourly values (so that you can get next day forecast for precipitation and temperature and use it in automation for heating and irrigation for example).
And I'd also like to add high/low temperatures and total precipitation to the forecast.
Optionally, I think it would also make sense for the wind_speed to check the max daily value than a snapshot at noon.

**Comment by Danielhiversen** [comment]
Fixed by https://github.com/Danielhiversen/pyMetno/pull/15
