### ISSUE TITLE
Please keep SDIST source on Pypi

### ISSUE THREAD

**Issue by onkelbeh** [Danielhiversen/pyMetno#17]
Hi Daniel,

I am using PyMetno for [Gentoo Repo for Home Assistant](https://github.com/onkelbeh/HomeAssistantRepository/tree/master/dev-python/PyMetno).
Could you please keep a Source on Pypi in SDIST format, so it could furthermore use Gentoo's mirror system?

It is missing in [Version 0.5.1](https://pypi.org/project/PyMetno/0.5.1/#files).
For [0.5.1 I am currently using a direct link](https://github.com/onkelbeh/HomeAssistantRepository/commit/571f8b1a435975ae31fccbe55405a9715809f043) to Github

Thanks.

**Comment by Danielhiversen** [comment]
Fixed

**Comment by onkelbeh** [comment]
Thanks. Works perfect again.
For completeness, just saw: Pypi API is still delivering an emtpy license string.
